# DB
quarkus.datasource.db-kind=mariadb
quarkus.datasource.username=${MARIA_USER:admin}
quarkus.datasource.password=${MARIA_PASSWORD:admin}
quarkus.datasource.jdbc.url=${MARIA_URL:jdbc:mariadb://localhost:3306/vbs}
quarkus.datasource.jdbc.max-size=10
quarkus.hibernate-orm.database.generation=drop-and-create
