-- sample vehicles
INSERT INTO vehicle (license_plate, name, manufacturer, model, created, updated) VALUES
('A-A-1111', 'Audi A5', 'Audi', 'A5', NOW(), NOW()),
('B-B-2222', 'BMW 3 Series', 'BMW', '3 Series', NOW(), NOW()),
('C-C-3333', 'VW Jetta', 'Volkswagen', 'Jetta', NOW(), NOW()),
('D-D-4444', 'Mercedes Sprinter', 'Mercedes Benz', 'Sprinter', NOW(), NOW()),
('E-E-5555', 'Subaru Outback', 'Subaru', 'Outback', NOW(), NOW()),
('F-F-6666', 'Smart Fortwo', 'Smart', 'Fortwo', NOW(), NOW()),
('G-G-7777', 'Fiat 500L', 'Fiat', '500L', NOW(), NOW()),
('H-H-8888', 'Peugeot 505', 'Peugeot', '505', NOW(), NOW()),
('I-I-9999', 'Suzuki Ltf400', 'Suzuki Ltf400', 'Ltf400', NOW(), NOW()),
('J-J-1234', 'Mini Cooper', 'MINI', 'Cooper', NOW(), NOW()),
('K-K-2222', 'Ford F350', 'Ford', 'F350', NOW(), NOW()),
('L-L-2323', 'Chevrolet Corvette', 'Chevrolet', 'Corvette', NOW(), NOW()),
('M-M-1414', 'Subaru Forester', 'Subaru', 'Forester', NOW(), NOW()),
('N-N-1515', 'Hyundai Santa Fe', 'Hyundai', 'Santa Fe', NOW(), NOW()),
('O-O-1515', 'Nissan Juke', 'Nissan', 'Juke', NOW(), NOW()),
('P-P-1515', 'Buick LaCrosse', 'Buick', 'LaCrosse', NOW(), NOW()),
('Q-Q-1515', 'Ferrari Superamerica', 'Ferrari', 'Superamerica', NOW(), NOW()),
('R-R-1515', 'HUMMER H2', 'HUMMER', 'H2', NOW(), NOW()),
('S-S-1513', 'Mazda MAZDA3', 'Mazda', 'MAZDA3', NOW(), NOW()),
('T-T-1513', 'Volvo VNL', 'Volvo', 'VNL', NOW(), NOW()),
('U-U-5678', 'Audi A4', 'Audi', 'A4', NOW(), NOW()),
('V-V-5678', 'BMW M3', 'BMW', 'M3', NOW(), NOW()),
('W-W-6799', 'Ford Mustang', 'Ford', 'Mustang', NOW(), NOW()),
('X-X-1903', 'Toyota Corolla', 'Toyota', 'Corolla', NOW(), NOW()),
('Y-Y-1903', 'Toyota Yaris', 'Toyota', 'Yaris', NOW(), NOW()),
('Z-Z-1993', 'Lotos Various', 'Lotus', 'Various', NOW(), NOW());

-- sample users
INSERT INTO "user" (email, first_name, last_name, created, updated) VALUES
('john.doe@example.com', 'John', 'Doe', NOW(), NOW()),
('jane.smith@example.com', 'Jane', 'Smith', NOW(), NOW()),
('bob.johnson@example.com', 'Bob', 'Johnson', NOW(), NOW()),
('alice.williams@example.com', 'Alice', 'Williams', NOW(), NOW()),
('charlie.brown@example.com', 'Charlie', 'Brown', NOW(), NOW()),
('mary.jones@example.com', 'Mary', 'Jones', NOW(), NOW()),
('james.davis@example.com', 'James', 'Davis', NOW(), NOW()),
('patricia.miller@example.com', 'Patricia', 'Miller', NOW(), NOW()),
('robert.wilson@example.com', 'Robert', 'Wilson', NOW(), NOW()),
('jennifer.moore@example.com', 'Jennifer', 'Moore', NOW(), NOW()),
('michael.taylor@example.com', 'Michael', 'Taylor', NOW(), NOW()),
('linda.anderson@example.com', 'Linda', 'Anderson', NOW(), NOW()),
('william.thomas@example.com', 'William', 'Thomas', NOW(), NOW()),
('elizabeth.jackson@example.com', 'Elizabeth', 'Jackson', NOW(), NOW()),
('david.white@example.com', 'David', 'White', NOW(), NOW()),
('barbara.harris@example.com', 'Barbara', 'Harris', NOW(), NOW()),
('richard.martin@example.com', 'Richard', 'Martin', NOW(), NOW()),
('susan.thompson@example.com', 'Susan', 'Thompson', NOW(), NOW()),
('joseph.garcia@example.com', 'Joseph', 'Garcia', NOW(), NOW()),
('jessica.martinez@example.com', 'Jessica', 'Martinez', NOW(), NOW()),
('thomas.robinson@example.com', 'Thomas', 'Robinson', NOW(), NOW()),
('sarah.clark@example.com', 'Sarah', 'Clark', NOW(), NOW()),
('charles.rodriguez@example.com', 'Charles', 'Rodriguez', NOW(), NOW()),
('karen.lewis@example.com', 'Karen', 'Lewis', NOW(), NOW()),
('james.hernandez@example.com', 'James', 'Hernandez', NOW(), NOW()),
('patricia.schmidt@example.com', 'Patricia', 'Schmidt', NOW(), NOW()),
('robert.gonzalez@example.com', 'Robert', 'Gonzalez', NOW(), NOW()),
('jennifer.reyes@example.com', 'Jennifer', 'Reyes', NOW(), NOW()),
('michael.pollock@example.com', 'Michael', 'Pollock', NOW(), NOW()),
('linda.brown@example.com', 'Linda', 'Brown', NOW(), NOW());